/**
 * Têtes, coiffures et expressions des joueurs : grilles de pixels originales, indexées sur les
 * emplacements de couleur (voir `src/match/render/sprites/canvas.ts`). Tête vue de face
 * (symétrique), lumière en haut à gauche : la seule ombre de peau est sur le côté droit.
 * Intérieur de 16×16, cheveux compris ; le contour automatique en fait 18×18.
 *   1/2/3 peau claire/base/ombre · r/h/H cheveux reflet/base/ombre · w blanc · n trait sombre
 *   S couleur secondaire de l'équipe (bandeau)
 */

/** Côté intérieur d'une tête (px), sans le contour. */
export const HEAD_GRID = 16;

/** 5 formes de tête, 16×16 (le haut est en général couvert par les cheveux). */
export const HEADS: readonly (readonly string[])[] = [
  // ronde
  [
    '.....111122.....',
    '...1111222222...',
    '..112222222222..',
    '.11222222222222.',
    '.12222222222223.',
    '1222222222222223',
    '1222222222222223',
    '2222222222222223',
    '2222222222222223',
    '2222222222222223',
    '2222222222222223',
    '.22222222222223.',
    '.22222222222233.',
    '..222222222233..',
    '...2222222233...',
    '.....222233.....',
  ],
  // carrée
  [
    '..111112222222..',
    '.11111222222222.',
    '1112222222222222',
    '1122222222222223',
    '1222222222222223',
    '1222222222222223',
    '2222222222222223',
    '2222222222222223',
    '2222222222222223',
    '2222222222222223',
    '2222222222222223',
    '2222222222222223',
    '2222222222222233',
    '.222222222222233',
    '.22222222222233.',
    '..222222222333..',
  ],
  // longue
  [
    '.....111122.....',
    '....11122222....',
    '...1122222222...',
    '..112222222222..',
    '..122222222223..',
    '.12222222222223.',
    '.12222222222223.',
    '.22222222222223.',
    '.22222222222223.',
    '.22222222222223.',
    '.22222222222223.',
    '..222222222223..',
    '..222222222233..',
    '...2222222233...',
    '....22222233....',
    '.....222233.....',
  ],
  // large
  [
    '...1111122222...',
    '.11111222222222.',
    '1112222222222222',
    '1122222222222223',
    '1222222222222223',
    '1222222222222223',
    '2222222222222223',
    '2222222222222223',
    '2222222222222223',
    '2222222222222223',
    '2222222222222223',
    '2222222222222223',
    '.22222222222223.',
    '.22222222222233.',
    '..222222222233..',
    '....22222233....',
  ],
  // ovale
  [
    '.....111122.....',
    '...1112222222...',
    '..112222222222..',
    '.11222222222222.',
    '.12222222222223.',
    '1222222222222223',
    '1222222222222223',
    '2222222222222223',
    '2222222222222223',
    '2222222222222223',
    '.22222222222223.',
    '.22222222222223.',
    '..222222222223..',
    '..222222222233..',
    '...2222222233...',
    '.....222233.....',
  ],
];

export type Expression = 'neutre' | 'concentree' | 'joyeuse';

/**
 * Expressions du visage vu en diagonale (de 3/4, tourné vers la droite ; vers la gauche, le
 * dessin est retourné), posées par-dessus la tête et les cheveux. L'œil proche (côté qui
 * s'éloigne) a 2×3 de blanc, l'œil éloigné 1 colonne contre le bord, les iris regardent dans le
 * sens de la course. Sourcils de 4 px et 2 px, nez de 3 px d'ombre de peau et bouche décalés vers
 * le sens de la course. L'oreille (côté qui s'éloigne) est posée par `headLayer`.
 * Aucun pixel sombre sur les joues.
 */
export const EXPRESSIONS: Readonly<Record<Expression, readonly string[]>> = {
  neutre: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '....nnnn....nn..',
    '.....wwn....wn..',
    '.....wwn....wn..',
    '.....wwn....wn..',
    '..........3.....',
    '..........33....',
    '................',
    '.........nnn....',
    '................',
    '................',
  ],
  concentree: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '....n........n..',
    '.....nnn....n...',
    '.....wwn....wn..',
    '.....wwn....wn..',
    '.....wwn....wn..',
    '..........3.....',
    '..........33....',
    '................',
    '.........nnn....',
    '................',
    '................',
  ],
  joyeuse: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '....nnnn....nn..',
    '................',
    '.....wwn....wn..',
    '.....wwn....wn..',
    '.....wwn....wn..',
    '..........3.....',
    '..........33....',
    '................',
    '........nwwn....',
    '.........nn.....',
    '................',
  ],
};

/** Oreille du côté qui s'éloigne (visage en diagonale) : colonne et rangées, au ton d'ombre. */
export const EAR = { col: 1, rows: [8, 9, 10] } as const;

/** Rangées occupées par les yeux dans une expression (pour les tests et le gros plan). */
export const EYE_ROWS = [7, 8, 9] as const;

export interface HairStyle {
  name: string;
  /** 16×16, dans la même boîte que la tête. */
  grid: readonly string[];
  /** La même coiffure vue de dos (16×16) : la nuque reste en peau sous les cheveux. */
  back: readonly string[];
  /** Coiffure plaquée : ne peint que sur la tête (pas de volume qui dépasse). */
  clip: boolean;
}

const EMPTY = '................';

/** 10 coiffures, toutes dans la boîte de 16×16 : la tête, cheveux compris, fait 18×18 avec le contour. */
export const HAIRS: readonly HairStyle[] = [
  {
    name: 'ras',
    clip: true,
    grid: [
      'HHHHHHHHHHHHHHHH',
      'HhHHhHHHHhHHHhHH',
      'HHHhHHHhHHHHhHHH',
      'HhHHHHhHHHhHHHHH',
      'HH............HH',
      'H..............H',
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
    ],
    back: [
      'HHHHHHHHHHHHHHHH',
      'HhHHhHHHHhHHHhHH',
      'HHHhHHHhHHHHhHHH',
      'HhHHHHhHHHhHHHHH',
      'HHHHhHHHHHHhHHHH',
      'HHhHHHHHhHHHHHhH',
      'HHHHHhHHHHHHHHHH',
      'HhHHHHHHHhHHHhHH',
      'HHHHhHHHHHHHHHHH',
      '.HHHHHHHHHHHHHH.',
      '..HHHHHHHHHHHH..',
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
    ],
  },
  {
    name: 'court',
    clip: false,
    grid: [
      '....rrhhhhhh....',
      '..rrhhhhhhhhhh..',
      '.rhhhhhhhhhhhhH.',
      'rhhhhhhhhhhhhhHH',
      'hhhhhhhhhhhhhhHH',
      'hh............HH',
      'h..............H',
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
    ],
    back: [
      '....rrhhhhhh....',
      '..rrhhhhhhhhhh..',
      '.rhhhhhhhhhhhhH.',
      'rhhhhhhhhhhhhhHH',
      'hhhhhhhhhhhhhhHH',
      'hhhhhhhhhhhhhhHH',
      'hhhhhhhhhhhhhHHH',
      'hhhhhhhhhhhhhHHH',
      'hhhhhhhhhhhhHHHH',
      '.hhhhhhhhhhhHHH.',
      '..hhhhhhhhhHHH..',
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
    ],
  },
  {
    name: 'afro',
    clip: false,
    grid: [
      '...rrhhhhhhhh...',
      '.rrhhhhhhhhhhhh.',
      'rhhhhhhhhhhhhhhH',
      'hhhhhhhhhhhhhhhH',
      'hhhhhhhhhhhhhhHH',
      'hhhhhhhhhhhhhhHH',
      'hhh..........hHH',
      'hh............HH',
      'hh............HH',
      'h..............H',
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
    ],
    back: [
      '...rrhhhhhhhh...',
      '.rrhhhhhhhhhhhh.',
      'rhhhhhhhhhhhhhhH',
      'hhhhhhhhhhhhhhhH',
      'hhhhhhhhhhhhhhHH',
      'hhhhhhhhhhhhhhHH',
      'hhhhhhhhhhhhhhHH',
      'hhhhhhhhhhhhhhHH',
      'hhhhhhhhhhhhhHHH',
      'hhhhhhhhhhhhhHHH',
      '.hhhhhhhhhhhHHH.',
      '..hhhhhhhhhHHH..',
      '....hhhhhhHH....',
      EMPTY,
      EMPTY,
      EMPTY,
    ],
  },
  {
    name: 'tresses',
    clip: true,
    grid: [
      'hHhHhHhHhHhHhHhH',
      'rHrHrHrHrHrHrHrH',
      'hHhHhHhHhHhHhHhH',
      'hHhHhHhHhHhHhHhH',
      'hH............hH',
      'h..............H',
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
    ],
    back: [
      'hHhHhHhHhHhHhHhH',
      'rHrHrHrHrHrHrHrH',
      'hHhHhHhHhHhHhHhH',
      'hHhHhHhHhHhHhHhH',
      'hHhHhHhHhHhHhHhH',
      'hHhHhHhHhHhHhHhH',
      'hHhHhHhHhHhHhHhH',
      'hHhHhHhHhHhHhHhH',
      'hHhHhHhHhHhHhHhH',
      'hHhHhHhHhHhHhHhH',
      '.HhHhHhHhHhHhHh.',
      '..H.H.H..H.H.H..',
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
    ],
  },
  {
    name: 'chignon',
    clip: false,
    grid: [
      '......HrrH......',
      '.....HhhhhH.....',
      '...hhhhhhhhhh...',
      '.rhhhhhhhhhhhhH.',
      'rhhhhhhhhhhhhhHH',
      'hhh..hhhhhh..hHH',
      'h..............H',
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
    ],
    back: [
      '......HrrH......',
      '.....HhhhhH.....',
      '...hhhhhhhhhh...',
      '.rhhhHHHHHhhhhH.',
      'rhhhHhhhhhHhhhHH',
      'hhhhHhhhhhHhhhHH',
      'hhhhhHHHHHhhhhHH',
      'hhhhhhhhhhhhhHHH',
      'hhhhhhhhhhhhhHHH',
      '.hhhhhhhhhhhHHH.',
      '..hhhhhhhhhHH...',
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
    ],
  },
  {
    name: 'bandeau',
    clip: true,
    grid: [
      'hhhhhhhhhhhhhhhh',
      'rhhhhhhhhhhhhhhH',
      'hhhhhhhhhhhhhhHH',
      'SSSSSSSSSSSSSSSS',
      'SSSSSSSSSSSSSSSS',
      'hh............HH',
      'h..............H',
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
    ],
    back: [
      'hhhhhhhhhhhhhhhh',
      'rhhhhhhhhhhhhhhH',
      'hhhhhhhhhhhhhhHH',
      'SSSSSSSSSSSSSSSS',
      'SSSSSSSSSSSSSSSS',
      'hhhhhhhhhhhhhhHH',
      'hhhhhhhhhhhhhhHH',
      'hhhhhhhhhhhhhHHH',
      'hhhhhhhhhhhhhHHH',
      '.hhhhhhhhhhhHHH.',
      '..hhhhhhhhhHH...',
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
    ],
  },
  {
    name: 'chauve',
    clip: true,
    grid: [
      EMPTY,
      '....11..........',
      '...11...........',
      '...1............',
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
    ],
    back: [
      EMPTY,
      '....11..........',
      '...11...........',
      '...1............',
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
    ],
  },
  {
    name: 'frange',
    clip: false,
    grid: [
      '....rrhhhhhh....',
      '..rrhhhhhhhhhh..',
      '.rhhhhhhhhhhhhH.',
      'rhhhhhhhhhhhhhHH',
      'hhhhhhhhhhhh.hHH',
      'hhhhhhhh.....hHH',
      'hh............HH',
      'h..............H',
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
    ],
    back: [
      '....rrhhhhhh....',
      '..rrhhhhhhhhhh..',
      '.rhhhhhhhhhhhhH.',
      'rhhhhhhhhhhhhhHH',
      'hhhhhhhhhhhhhhHH',
      'hhhhhhhhhhhhhhHH',
      'hhhhhhhhhhhhhHHH',
      'hhhhhhhhhhhhhHHH',
      'hhhhhhhhhhhhHHHH',
      '.hhhhhhhhhhhHHH.',
      '..hhhhhhhhhHHH..',
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
    ],
  },
  {
    name: 'degrade',
    clip: true,
    grid: [
      'hhhhhhhhhhhhhhhh',
      'rhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhH',
      'HhhhhhhhhhhhhhhH',
      'H..............H',
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
    ],
    back: [
      'hhhhhhhhhhhhhhhh',
      'rhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhH',
      'hhhhhhhhhhhhhhHH',
      'HhhhhhhhhhhhhhHH',
      'HHhhhhhhhhhhhHHH',
      'HHHhHhHhHhHhHHHH',
      '.H.H.H.H.H.H.H.H',
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
    ],
  },
  {
    name: 'barbe',
    clip: true,
    grid: [
      'HHHHHHHHHHHHHHHH',
      'HhHHhHHHHhHHHhHH',
      'HHHhHHHhHHHHhHHH',
      'HH............HH',
      'H..............H',
      EMPTY,
      EMPTY,
      EMPTY,
      EMPTY,
      'h..............h',
      'hh............hh',
      'hhh..........hhh',
      'hhhh........hhhh',
      'hhhhhh....hhhhhh',
      '.hhhhhhhhhhhhhh.',
      '..hhhhhhhhhhhh..',
    ],
    back: [
      'HHHHHHHHHHHHHHHH',
      'HhHHhHHHHhHHHhHH',
      'HHHhHHHhHHHHhHHH',
      'HhHHHHhHHHhHHHHH',
      'HHHHhHHHHHHhHHHH',
      'HHhHHHHHhHHHHHhH',
      'HHHHHhHHHHHHHHHH',
      'HhHHHHHHHhHHHhHH',
      'HHHHhHHHHHHHHHHH',
      '.HHHHHHHHHHHHHH.',
      '..HHHHHHHHHHHH..',
      'h..............h',
      'hh............hh',
      '.h............h.',
      EMPTY,
      EMPTY,
    ],
  },
];
