/**
 * Planche de styles (incrément 15 quater) : le même ailier dessiné à la main, pixel par pixel,
 * dans trois styles candidats, pour que Matheo choisisse le style des joueurs. Grilles
 * originales, indexées sur les emplacements de couleur (voir `src/match/render/sprites/canvas.ts`) :
 *   1/2/3 peau claire/base/ombre · r/h/H cheveux reflet/base/ombre · p/P/q équipe primaire
 *   claire/base/sombre · s/S/t équipe secondaire · k encre · w craie · n trait sombre · o contour
 * Le contour de la silhouette est posé à l'assemblage (`composeCandidate`) ; les grilles ne
 * dessinent que l'intérieur. Toutes les images regardent vers la droite.
 * Temporaire : les styles non retenus seront supprimés au 15 quinquies.
 */
import type { Expression } from './heads';

export type StyleId = 'A' | 'B' | 'C';
export type CandidatePose = 'arret' | 'course' | 'dribble' | 'courseHaut' | 'tir';
export type CandidateHair = 'court' | 'afro' | 'bandeau';

export const CANDIDATE_POSES: readonly CandidatePose[] = ['arret', 'course', 'dribble', 'courseHaut', 'tir'];
export const CANDIDATE_HAIRS: readonly CandidateHair[] = ['court', 'afro', 'bandeau'];

export interface CandidateBody {
  /** Corps sans la tête ; la dernière rangée est posée sur la rangée au-dessus du sol. */
  rows: readonly string[];
  /** Colonne du centre du joueur (posée au milieu du cadre). */
  center: number;
  /** Coin haut-gauche de la tête, en coordonnées de la grille du corps. */
  head: { x: number; y: number };
  /** Pixels posés par-dessus la tête (bras levé, main), même taille que `rows`. */
  over?: readonly string[];
  /** Zone du numéro (coin haut-gauche et largeur), sur le maillot. */
  number?: { x: number; y: number; width: number };
  /** Centre du ballon tenu, ou absent. */
  ball?: { x: number; y: number };
  /** Vue de dos (diagonale haut) : tête de dos, sans visage. */
  back?: boolean;
  expression?: Expression;
}

export interface CandidateHairGrids {
  front: readonly string[];
  back: readonly string[];
  /** Décalage de la grille des cheveux par rapport à la tête (afro plus large que le crâne). */
  offset?: { x: number; y: number };
}

export interface CandidateStyle {
  id: StyleId;
  name: string;
  /** Tête (forme et ombrage de la peau), vue en diagonale bas et en diagonale haut. */
  head: { front: readonly string[]; back: readonly string[] };
  hairs: Readonly<Record<CandidateHair, CandidateHairGrids>>;
  /** Visage de 3/4, posé par-dessus la tête et les cheveux. */
  expressions: Readonly<Record<Expression, readonly string[]>>;
  bodies: Readonly<Record<CandidatePose, CandidateBody>>;
}

// ---------------------------------------------------------------------------------------------
// A. Chibi net : grosse tête ronde, aplats et un ton d'ombre, contour seulement autour de la
// silhouette, yeux en points sombres.
// ---------------------------------------------------------------------------------------------

const A_HEAD_FRONT = [
  '......11122.....',
  '....111122222...',
  '...11122222222..',
  '..1112222222222.',
  '..1122222222223.',
  '.112222222222223',
  '.122222222222223',
  '.122222222222223',
  '3222222222222223',
  '3322222222222223',
  '3222222222222233',
  '.222222222222233',
  '..22222222222233',
  '...2222222222333',
  '.....222222233..',
  '.......22333....',
];

const A_HEAD_BACK = [
  '......11122.....',
  '....111122222...',
  '...11122222222..',
  '..1112222222222.',
  '..1122222222223.',
  '.112222222222223',
  '.122222222222223',
  '.122222222222223',
  '.122222222222223',
  '.122222222222223',
  '.122222222222223',
  '.22222222222222.',
  '..2222222222223.',
  '...22222222223..',
  '.....2222223....',
  '.......2233.....',
];

const STYLE_A: CandidateStyle = {
  id: 'A',
  name: 'CHIBI NET',
  head: { front: A_HEAD_FRONT, back: A_HEAD_BACK },
  hairs: {
    court: {
      front: [
        '.....hhhhhh.....',
        '...hhrrhhhhhh...',
        '..hrrhhhhhhhhh..',
        '.hrhhhhhhhhhhhH.',
        '.hhhhhhhhhhhhHH.',
        'hhhhhh.......HHH',
        'hhhhH...........',
        'hhhH............',
        '.hH.............',
      ],
      back: [
        '.....hhhhhh.....',
        '...hhrrhhhhhh...',
        '..hrrhhhhhhhhh..',
        '.hrhhhhhhhhhhhH.',
        '.hhhhhhhhhhhhHH.',
        'hhhhhhhhhhhhhHHH',
        'hhhhhhhhhhhhHHHH',
        'hhhhhhhhhhhhHHH.',
        'hhhhhhhhhhhHHH..',
        '.hhhhhhhhhHHH...',
        '.HHhhhhhhHH.....',
      ],
    },
    afro: {
      offset: { x: -2, y: -3 },
      front: [
        '......hhhhhhh.......',
        '....hhrrhhhhhhh.....',
        '...hrrrhhhhhhhhh....',
        '..hrrhhhhhhhhhhhH...',
        '.hrrhhhhhhhhhhhhHH..',
        '.hrhhhhhhhhhhhhhHHH.',
        'hhhhhhhhhhhhhhhhHHH.',
        'hhhhhhhhhhhhhhhhhHHH',
        'hhhhhhhh.......hhHHH',
        'hhhhhhH.........hHH.',
        'hhhhhH...........H..',
        '.hhhH...............',
        '.hhH................',
        '..H.................',
      ],
      back: [
        '......hhhhhhh.......',
        '....hhrrhhhhhhh.....',
        '...hrrrhhhhhhhhh....',
        '..hrrhhhhhhhhhhhH...',
        '.hrrhhhhhhhhhhhhHH..',
        '.hrhhhhhhhhhhhhhHHH.',
        'hhhhhhhhhhhhhhhhHHH.',
        'hhhhhhhhhhhhhhhhhHHH',
        'hhhhhhhhhhhhhhhhhHHH',
        'hhhhhhhhhhhhhhhhHHHH',
        'hhhhhhhhhhhhhhhHHHH.',
        '.hhhhhhhhhhhhhHHHH..',
        '.hhhhhhhhhhhHHHHH...',
        '..HHhhhhhhhHHHH.....',
        '....HHHHHHHHH.......',
      ],
    },
    bandeau: {
      front: [
        '.....hhhhhh.....',
        '...hhrrhhhhhh...',
        '..hrrhhhhhhhhh..',
        '.SSSSSSSSSSSSSt.',
        '.SSSSSSSSSSSStt.',
        'hhhh.........HHH',
        'hhhH............',
        'hhH.............',
        '.H..............',
      ],
      back: [
        '.....hhhhhh.....',
        '...hhrrhhhhhh...',
        '..hrrhhhhhhhhh..',
        '.SSSSSSSSSSSSSt.',
        '.SSSSSSSSSSSStt.',
        'hhhhhhhhhhhhhHHH',
        'hhhhhhhhhhhhHHHH',
        'hhhhhhhhhhhhHHH.',
        'hhhhhhhhhhhHHH..',
        '.hhhhhhhhhHHH...',
        '.HHhhhhhhHH.....',
      ],
    },
  },
  expressions: {
    neutre: [
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '.......n....n...',
      '.......n....n...',
      '................',
      '................',
      '...........nn...',
      '................',
      '................',
      '................',
      '................',
    ],
    concentree: [
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '......nn...nn...',
      '.......n....n...',
      '.......n....n...',
      '................',
      '................',
      '...........nn...',
      '................',
      '................',
      '................',
      '................',
    ],
    joyeuse: [
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '.......n....n...',
      '.......n....n...',
      '................',
      '..........n..n..',
      '...........nn...',
      '................',
      '................',
      '................',
      '................',
    ],
  },
  bodies: {
    arret: {
      center: 11,
      head: { x: 4, y: -16 },
      number: { x: 8, y: 3, width: 8 },
      rows: [
        '..........3333........',
        '.....12PPS2233SP33....',
        '....122PPPSSSSPPq33...',
        '....223pPPPPPPPPqq3...',
        '....223pPPPPPPPPqq3...',
        '....223pPPPPPPPPqq3...',
        '....223pPPPPPPPPqq3...',
        '....223pPPPPPPPPqq3...',
        '....223.pPPPPPPPqq3...',
        '....223.pPPPPPPPqq3...',
        '...2222.pPPPPPPqqq33..',
        '...2223SSSSSSSSSttt3..',
        '....33.SPPPPPPPPqqq...',
        '.......SPPPPqqPPPqq...',
        '.......SPPPq..qPPqq...',
        '........223...333.....',
        '........223...333.....',
        '........223...333.....',
        '........223...www.....',
        '........223..kkkk.....',
        '........www..kkkkk....',
        '.......kkkk..kkkkkk...',
        '.......kkkkk.wwwwww...',
        '.......kkkkkk.........',
        '.......wwwwww.........',
      ],
    },
    course: {
      center: 11,
      head: { x: 4, y: -16 },
      number: { x: 8, y: 3, width: 8 },
      rows: [
        '..........3333........',
        '.....12PPS2233SP33....',
        '....122PPPSSSSPPq33...',
        '....223pPPPPPPPPqq3...',
        '....223pPPPPPPPPqq3...',
        '....223pPPPPPPPPqq3...',
        '.....223PPPPPPPPqq3...',
        '......2233PPPPPPqq3...',
        '.......2223PPPPPqq33..',
        '........2223PPPPqq33..',
        '.........333PPPqqq....',
        '.......SSSSSSSSSttt...',
        '.......SPPPPPPPPqqq...',
        '.......SPPPPqqPPPqq...',
        '.......SPPPq..qPPPq...',
        '.......223.....333....',
        '......223......3333...',
        '.....223........333...',
        '....www.........333...',
        '..kkkk...........www..',
        '.kkkkk..........kkkk..',
        '.kkkkkk.........kkkkk.',
        '.wwwwww.........kkkkkk',
        '................wwwwww',
        '......................',
      ],
    },
    dribble: {
      center: 11,
      head: { x: 4, y: -16 },
      number: { x: 8, y: 3, width: 8 },
      ball: { x: 21, y: 20 },
      rows: [
        '..........3333..........',
        '.....12PPS2233SP33......',
        '...1122PPPSSSSPPq333....',
        '..1223pPPPPPPPPPqq3332..',
        '.1223.pPPPPPPPPPqq..332.',
        '.223..pPPPPPPPPPqq...33.',
        '.222..pPPPPPPPPPqq...33.',
        '..22..pPPPPPPPPPqq...222',
        '......pPPPPPPPPPqq...222',
        '.......pPPPPPPPqq....233',
        '.......pPPPPPPqqq.......',
        '.......SSSSSSSSSttt.....',
        '.......SPPPPPPPPqqq.....',
        '.......SPPPPqqPPPqq.....',
        '.......SPPPq..qPPPq.....',
        '.......223.....333......',
        '.......223.....333......',
        '......223.......333.....',
        '......223.......333.....',
        '......www.......www.....',
        '.....kkkk......kkkk.....',
        '.....kkkkk.....kkkkk....',
        '.....kkkkkk....kkkkkk...',
        '.....wwwwww....wwwwww...',
      ],
    },
    courseHaut: {
      center: 11,
      head: { x: 3, y: -16 },
      number: { x: 6, y: 3, width: 8 },
      back: true,
      rows: [
        '.........3333.........',
        '....33PPPPPPPPP22.....',
        '...333pPPPPPPPPqq22...',
        '...333pPPPPPPPPqq22...',
        '...333pPPPPPPPPqq22...',
        '...333pPPPPPPPPqq223..',
        '...333pPPPPPPPPqq.223.',
        '....33pPPPPPPPPqq..222',
        '....333pPPPPPPPqq..222',
        '....333pPPPPPPPqq..33.',
        '.......pPPPPPPqqq.....',
        '.....SSSSSSSSSSttt....',
        '.....SPPPPPPPPPqqS....',
        '.....SPPPPPPPPPqqS....',
        '.....SPPPP..PPPqqS....',
        '......333....223......',
        '......333....223......',
        '......333....223......',
        '......333....223......',
        '......www....223......',
        '.....kkkk....www......',
        '.....kkkkk..kkkk......',
        '.....wwwww..kkkkk.....',
        '............kkkkk.....',
        '............wwwww.....',
      ],
    },
    tir: {
      center: 11,
      head: { x: 4, y: 6 },
      number: { x: 8, y: 25, width: 8 },
      ball: { x: 12, y: 2 },
      expression: 'concentree',
      rows: [
        '........................',
        '........................',
        '........................',
        '........................',
        '.....222........233.....',
        '.....222........233.....',
        '.....223........333.....',
        '....223..........233....',
        '...223............233...',
        '..223...............233.',
        '..223...............233.',
        '.223................233.',
        '.233................233.',
        '.233................333.',
        '.223................233.',
        '.223................233.',
        '.223................233.',
        '.223................233.',
        '.223................233.',
        '.223................233.',
        '.223................233.',
        '..223...............233.',
        '...223....3333....333...',
        '....122PPS2233SP333.....',
        '.....12PPPSSSSPPq3......',
        '.......pPPPPPPPPqq......',
        '.......pPPPPPPPPqq......',
        '.......pPPPPPPPPqq......',
        '.......pPPPPPPPPqq......',
        '.......pPPPPPPPPqq......',
        '........pPPPPPPPqq......',
        '........pPPPPPPPqq......',
        '........pPPPPPPqqq......',
        '.......SSSSSSSSSttt.....',
        '.......SPPPPPPPPqqq.....',
        '.......SPPPPqqPPPqq.....',
        '.......SPPPq..qPPqq.....',
        '........223...333.......',
        '........223...333.......',
        '........223...333.......',
        '........www...www.......',
        '........kkkk..kkkk......',
        '........kkkkk.kkkkk.....',
        '........wwwww.wwwww.....',
        '........................',
        '........................',
        '........................',
      ],
    },
  },
};

// ---------------------------------------------------------------------------------------------
// B. Sportif 16-bit : tête plus petite (~30 %), corps athlétique en V, bras longs, 3 tons
// (reflet, base, ombre), sourcils au ton sombre des cheveux, œil avec son blanc.
// ---------------------------------------------------------------------------------------------

const B_HEAD_FRONT = [
  '....1112....',
  '..11122222..',
  '.1112222222.',
  '.1122222222.',
  '112222222223',
  '122222222223',
  '322222222223',
  '332222222223',
  '322222222233',
  '.22222222233',
  '..222222233.',
  '...22222333.',
  '.....2233...',
];

const B_HEAD_BACK = [
  '....1112....',
  '..11122222..',
  '.1112222222.',
  '.1122222222.',
  '112222222223',
  '122222222223',
  '122222222223',
  '122222222233',
  '122222222233',
  '.22222222233',
  '..222222233.',
  '...2222233..',
  '.....2233...',
];

const STYLE_B: CandidateStyle = {
  id: 'B',
  name: 'SPORTIF 16-BIT',
  head: { front: B_HEAD_FRONT, back: B_HEAD_BACK },
  hairs: {
    court: {
      front: [
        '...hhhhhh...',
        '.hhrrhhhhhh.',
        'hhrhhhhhhhhH',
        'hhhhhhhhhHHH',
        'hhhhH.....HH',
        'hhhH........',
        'hhH.........',
      ],
      back: [
        '...hhhhhh...',
        '.hhrrhhhhhh.',
        'hhrhhhhhhhhH',
        'hhhhhhhhhHHH',
        'hhhhhhhhhHHH',
        'hhhhhhhhHH..',
        'hhhhhhhhH...',
        'hhhhhhhHH...',
        'hhhhhhhH....',
        '.HHhhhH.....',
      ],
    },
    afro: {
      offset: { x: -2, y: -3 },
      front: [
        '.....hhhhhh.....',
        '...hhrrhhhhhh...',
        '..hrrrhhhhhhhH..',
        '.hrrhhhhhhhhhHH.',
        '.hrhhhhhhhhhhhHH',
        'hhhhhhhhhhhhhhHH',
        'hhhhhhhh....hhHH',
        'hhhhhH.......HH.',
        'hhhhH...........',
        '.hhH............',
        '.hH.............',
      ],
      back: [
        '.....hhhhhh.....',
        '...hhrrhhhhhh...',
        '..hrrrhhhhhhhH..',
        '.hrrhhhhhhhhhHH.',
        '.hrhhhhhhhhhhhHH',
        'hhhhhhhhhhhhhhHH',
        'hhhhhhhhhhhhhhHH',
        'hhhhhhhhhhhhhHHH',
        'hhhhhhhhhhhhHHH.',
        '.hhhhhhhhhhHHH..',
        '.hhhhhhhhhHHH...',
        '..HHhhhhhHH.....',
        '....HHHHH.......',
      ],
    },
    bandeau: {
      front: [
        '...hhhhhh...',
        '.hhrrhhhhhh.',
        'SSSSSSSSSSSt',
        'SSSSSSSSSStt',
        'hhhh......HH',
        'hhhH........',
        'hhH.........',
      ],
      back: [
        '...hhhhhh...',
        '.hhrrhhhhhh.',
        'SSSSSSSSSSSt',
        'SSSSSSSSSStt',
        'hhhhhhhhhHHH',
        'hhhhhhhhHH..',
        'hhhhhhhhH...',
        'hhhhhhhHH...',
        'hhhhhhhH....',
        '.HHhhhH.....',
      ],
    },
  },
  expressions: {
    neutre: ['............', '............', '............', '............', '............', '....HH...H..', '....wn...n..', '..........3.', '.........33.', '........nn..', '............', '............', '............'],
    concentree: ['............', '............', '............', '............', '...H.....H..', '....HH..H...', '....wn...n..', '..........3.', '.........33.', '........nn..', '............', '............', '............'],
    joyeuse: ['............', '............', '............', '............', '............', '....HH...H..', '....wn...n..', '..........3.', '.........33.', '.......n..n.', '........nn..', '............', '............'],
  },
  bodies: {
    arret: {
      center: 11,
      head: { x: 6, y: -13 },
      number: { x: 8, y: 5, width: 8 },
      rows: [
        '.........2223.........',
        '.........2333.........',
        '.....11pS2233SPqq33...',
        '....112pPSSSSPPqq333..',
        '...1122pPPPPPPPqq333..',
        '....223pPPPPPPPqq33...',
        '....223pPPPPPPPqq33...',
        '....223pPPPPPPPqq33...',
        '....223pPPPPPPPqq33...',
        '....233.pPPPPPPqq33...',
        '....223.pPPPPPPqq33...',
        '....223.pPPPPPPqq33...',
        '....223.pPPPPPPqq33...',
        '....223.pPPPPPPqq33...',
        '....223SSSSSSSStt33...',
        '....223SpPPPPPPqq33...',
        '....223SpPPPPPPqq33...',
        '...2223SPPPPPPPqq33...',
        '...2233SPPPP.PPPq33...',
        '....33..223..233......',
        '........223..233......',
        '........223..233......',
        '........223..www......',
        '........223..kkkk.....',
        '........www..kkkkkk...',
        '.......kkkk..wwwwww...',
        '.......kkkkkk.........',
        '.......wwwwww.........',
      ],
    },
    course: {
      center: 11,
      head: { x: 6, y: -13 },
      number: { x: 8, y: 5, width: 8 },
      rows: [
        '.........2223.........',
        '.........2333.........',
        '.....11pS2233SPqq33...',
        '....112pPSSSSPPqq333..',
        '...1122pPPPPPPPqq333..',
        '....223pPPPPPPPqq.33..',
        '....223pPPPPPPPqq.33..',
        '.....223PPPPPPPqq..33.',
        '......223PPPPPPqq..33.',
        '.......2233PPPPqq..23.',
        '........2223PPPqq..22.',
        '.........2223PPqq.....',
        '..........333PPqq.....',
        '........PPPPPPPqq.....',
        '.......SSSSSSSStt.....',
        '.......SpPPPPPPqq.....',
        '.......SpPPPPPPqq.....',
        '.......SPPPPPPPqq.....',
        '.......SPPPP.PPPq.....',
        '.......223....233.....',
        '......223.....2333....',
        '.....223.......333....',
        '....223........333....',
        '...www.........www....',
        '.kkkk.........kkkk....',
        '.kkkkkk.......kkkkkk..',
        '.wwwwww.......wwwwww..',
        '......................',
      ],
    },
    dribble: {
      center: 11,
      head: { x: 6, y: -13 },
      number: { x: 8, y: 5, width: 8 },
      ball: { x: 21, y: 23 },
      rows: [
        '.........2223...........',
        '.........2333...........',
        '.....11pS2233SPqq33.....',
        '....112pPSSSSPPqq333....',
        '...1122pPPPPPPPqq3332...',
        '..1223.pPPPPPPPqq.3332..',
        '.1223..pPPPPPPPqq..333..',
        '.223...pPPPPPPPqq...233.',
        '.223...pPPPPPPPqq...223.',
        '..22...pPPPPPPPqq...223.',
        '.......pPPPPPPqq.....23.',
        '........pPPPPPPqq....233',
        '........pPPPPPPqq....222',
        '........pPPPPPPqq....233',
        '.......SSSSSSSStt.......',
        '.......SpPPPPPPqq.......',
        '.......SpPPPPPPqq.......',
        '.......SPPPPPPPqq.......',
        '.......SPPPP.PPPq.......',
        '.......223....233.......',
        '.......223....233.......',
        '......223......233......',
        '......223......233......',
        '......223......www......',
        '......www.....kkkk......',
        '.....kkkk.....kkkkkk....',
        '.....kkkkkk...wwwwww....',
        '.....wwwwww.............',
      ],
    },
    courseHaut: {
      center: 11,
      head: { x: 5, y: -13 },
      number: { x: 7, y: 5, width: 8 },
      back: true,
      rows: [
        '........3333..........',
        '........3333..........',
        '....33qPPPPPPPP21.....',
        '...333qpPPPPPPPq211...',
        '...333qpPPPPPPPqq2211.',
        '...333.pPPPPPPPqq.223.',
        '...333.pPPPPPPPqq.223.',
        '....33.pPPPPPPPqq..223',
        '....33.pPPPPPPPqq..223',
        '....333pPPPPPPPqq..222',
        '....333pPPPPPPPqq..233',
        '....333pPPPPPPPqq.....',
        '.....33pPPPPPPPqq.....',
        '.....33pPPPPPPPqq.....',
        '......SSSSSSSSSttt....',
        '......SpPPPPPPPqqS....',
        '......SpPPPPPPPqqS....',
        '......SPPPPPPPPqqS....',
        '......SPPPP.PPPqqS....',
        '.......333...223......',
        '.......333...223......',
        '.......333...223......',
        '.......www...223......',
        '......kkkk...223......',
        '......kkkkk..www......',
        '......wwwww.kkkk......',
        '............kkkkk.....',
        '............wwwww.....',
      ],
    },
    tir: {
      center: 11,
      head: { x: 6, y: 8 },
      number: { x: 8, y: 27, width: 8 },
      ball: { x: 12, y: 3 },
      expression: 'concentree',
      rows: [
        '.......................',
        '.......................',
        '.......................',
        '.......................',
        '.......................',
        '.....222........233....',
        '.....222........233....',
        '.....223........333....',
        '....223..........233...',
        '...223............233..',
        '...223.............233.',
        '..223..............233.',
        '..223..............233.',
        '..233..............233.',
        '..233..............333.',
        '..223..............233.',
        '..223..............233.',
        '..223..............233.',
        '..223..............233.',
        '..223..............233.',
        '..223..............233.',
        '...223...2223.....233..',
        '....223..2333....233...',
        '....112pS2233SPqq333...',
        '.....12pPSSSSPPqq3.....',
        '.......pPPPPPPPqq......',
        '.......pPPPPPPPqq......',
        '.......pPPPPPPPqq......',
        '.......pPPPPPPPqq......',
        '.......pPPPPPPPqq......',
        '........pPPPPPPqq......',
        '........pPPPPPPqq......',
        '........pPPPPPPqq......',
        '........pPPPPPPqq......',
        '........pPPPPPPqq......',
        '.......SSSSSSSStt......',
        '.......SpPPPPPPqq......',
        '.......SpPPPPPPqq......',
        '.......SPPPPPPPqq......',
        '.......SPPPP.PPPq......',
        '........223..233.......',
        '........223..233.......',
        '........223..233.......',
        '........www..www.......',
        '.......kkkk..kkkk......',
        '.......kkkkk.kkkkk.....',
        '.......wwwww.wwwww.....',
        '.......................',
        '.......................',
      ],
    },
  },
};

// ---------------------------------------------------------------------------------------------
// C. Minimal lisible : aplats sans ombre (seuls les membres éloignés sont plus sombres), formes
// simples et arrondies, deux points pour les yeux.
// ---------------------------------------------------------------------------------------------

const C_HEAD_FRONT = [
  '.....222222...',
  '...2222222222.',
  '..22222222222.',
  '.2222222222222',
  '.2222222222222',
  '22222222222222',
  '22222222222222',
  '22222222222222',
  '22222222222222',
  '.2222222222222',
  '.2222222222222',
  '..22222222222.',
  '....222222222.',
  '......22222...',
];

const C_HEAD_BACK = [
  '.....222222...',
  '...2222222222.',
  '..22222222222.',
  '.2222222222222',
  '.2222222222222',
  '.2222222222222',
  '.2222222222222',
  '.2222222222222',
  '.2222222222222',
  '.2222222222222',
  '.2222222222222',
  '..22222222222.',
  '....22222222..',
  '......2222....',
];

const STYLE_C: CandidateStyle = {
  id: 'C',
  name: 'MINIMAL LISIBLE',
  head: { front: C_HEAD_FRONT, back: C_HEAD_BACK },
  hairs: {
    court: {
      front: [
        '.....hhhhhh...',
        '...hhhhhhhhhh.',
        '..hhhhhhhhhhh.',
        '.hhhhhhhhhhhhh',
        '.hhhhh......hh',
        'hhhh..........',
        'hhh...........',
        '.h............',
      ],
      back: [
        '.....hhhhhh...',
        '...hhhhhhhhhh.',
        '..hhhhhhhhhhh.',
        '.hhhhhhhhhhhhh',
        '.hhhhhhhhhhhhh',
        '.hhhhhhhhhhhhh',
        '.hhhhhhhhhhh..',
        '.hhhhhhhhhhh..',
        '.hhhhhhhhhh...',
        '..hhhhhhhh....',
      ],
    },
    afro: {
      offset: { x: -2, y: -3 },
      front: [
        '......hhhhhh......',
        '....hhhhhhhhhh....',
        '...hhhhhhhhhhhh...',
        '..hhhhhhhhhhhhhh..',
        '.hhhhhhhhhhhhhhhh.',
        '.hhhhhhhhhhhhhhhh.',
        'hhhhhhhhhhhhhhhhhh',
        'hhhhhhh......hhhhh',
        'hhhhh.........hhh.',
        'hhhh..............',
        '.hh...............',
      ],
      back: [
        '......hhhhhh......',
        '....hhhhhhhhhh....',
        '...hhhhhhhhhhhh...',
        '..hhhhhhhhhhhhhh..',
        '.hhhhhhhhhhhhhhhh.',
        '.hhhhhhhhhhhhhhhh.',
        'hhhhhhhhhhhhhhhhhh',
        'hhhhhhhhhhhhhhhhhh',
        'hhhhhhhhhhhhhhhhh.',
        '.hhhhhhhhhhhhhhh..',
        '..hhhhhhhhhhhhh...',
        '...hhhhhhhhhhh....',
        '.....hhhhhhh......',
      ],
    },
    bandeau: {
      front: [
        '.....hhhhhh...',
        '...hhhhhhhhhh.',
        '..SSSSSSSSSSS.',
        '.SSSSSSSSSSSSS',
        '.hhh........hh',
        'hhh...........',
        'hh............',
        '.h............',
      ],
      back: [
        '.....hhhhhh...',
        '...hhhhhhhhhh.',
        '..SSSSSSSSSSS.',
        '.SSSSSSSSSSSSS',
        '.hhhhhhhhhhhhh',
        '.hhhhhhhhhhhhh',
        '.hhhhhhhhhhh..',
        '.hhhhhhhhhhh..',
        '.hhhhhhhhhh...',
        '..hhhhhhhh....',
      ],
    },
  },
  expressions: {
    neutre: ['..............', '..............', '..............', '..............', '..............', '..............', '..............', '.......n...n..', '.......n...n..', '..............', '..............', '..............', '..............', '..............'],
    concentree: ['..............', '..............', '..............', '..............', '..............', '..............', '..............', '.......n...n..', '..............', '..............', '..............', '..............', '..............', '..............'],
    joyeuse: ['..............', '..............', '..............', '..............', '..............', '..............', '..............', '.......n...n..', '.......n...n..', '..............', '.........n..n.', '..........nn..', '..............', '..............'],
  },
  bodies: {
    arret: {
      center: 10,
      head: { x: 4, y: -14 },
      number: { x: 7, y: 3, width: 7 },
      rows: [
        '.........222........',
        '....222PP222PP333...',
        '...222PPPPPPPPP333..',
        '...222PPPPPPPPP33...',
        '...222PPPPPPPPP33...',
        '...222PPPPPPPPP33...',
        '...222PPPPPPPPP33...',
        '...222PPPPPPPPP33...',
        '...222.PPPPPPP.33...',
        '...222.PPPPPPP.33...',
        '..2222.PPPPPPP.333..',
        '..2222.PPPPPPP.333..',
        '......SSSSSSSSS.....',
        '......PPPPPPPPP.....',
        '......PPPPPPPPP.....',
        '......PPPP.PPPP.....',
        '.......222..333.....',
        '.......222..333.....',
        '.......222..333.....',
        '.......222..333.....',
        '.......222..www.....',
        '.......222..kkkk....',
        '.......www..kkkkk...',
        '......kkkk..wwwww...',
        '......kkkkk.........',
        '......kkkkkk........',
        '......wwwwww........',
      ],
    },
    course: {
      center: 10,
      head: { x: 4, y: -14 },
      number: { x: 7, y: 3, width: 7 },
      rows: [
        '.........222........',
        '....222PP222PP333...',
        '...222PPPPPPPPP333..',
        '...222PPPPPPPPP33...',
        '....222PPPPPPPP.33..',
        '.....222PPPPPPP.33..',
        '......222PPPPPP..33.',
        '.......2222PPPP..33.',
        '........2222PPP.....',
        '........2222PPP.....',
        '.......PPPPPPPP.....',
        '.......PPPPPPPP.....',
        '......SSSSSSSSS.....',
        '......PPPPPPPPP.....',
        '......PPPPPPPPP.....',
        '......PPPP.PPPP.....',
        '......222...333.....',
        '.....222....3333....',
        '....222......333....',
        '...www.......333....',
        '..kkkk.......333....',
        '.kkkkk.......www....',
        '.kkkkkk.....kkkk....',
        '.wwwwww.....kkkkk...',
        '............kkkkkk..',
        '............wwwwww..',
        '....................',
      ],
    },
    dribble: {
      center: 10,
      head: { x: 4, y: -14 },
      number: { x: 7, y: 3, width: 7 },
      ball: { x: 19, y: 22 },
      rows: [
        '.........222..........',
        '....222PP222PP333.....',
        '..2222PPPPPPPPP3333...',
        '.222..PPPPPPPPP..333..',
        '.222..PPPPPPPPP...333.',
        '.222..PPPPPPPPP...333.',
        '..22..PPPPPPPPP...333.',
        '......PPPPPPPPP...333.',
        '.......PPPPPPP....333.',
        '.......PPPPPPP...3333.',
        '.......PPPPPPP...3333.',
        '.......PPPPPPP........',
        '......SSSSSSSSS.......',
        '......PPPPPPPPP.......',
        '......PPPPPPPPP.......',
        '......PPPP.PPPP.......',
        '......222...333.......',
        '......222...333.......',
        '.....222.....333......',
        '.....222.....333......',
        '.....222.....www......',
        '.....www....kkkk......',
        '....kkkk....kkkkk.....',
        '....kkkkk...wwwwww....',
        '....kkkkkk............',
        '....wwwwww............',
      ],
    },
    courseHaut: {
      center: 10,
      head: { x: 3, y: -14 },
      number: { x: 6, y: 3, width: 7 },
      back: true,
      rows: [
        '........222.........',
        '...333PPPPPPP222....',
        '..333PPPPPPPPP2222..',
        '..333PPPPPPPPP..222.',
        '..333PPPPPPPPP..222.',
        '..333PPPPPPPPP..222.',
        '...33PPPPPPPPP..222.',
        '...33PPPPPPPPP..222.',
        '...333PPPPPPP.......',
        '...333PPPPPPP.......',
        '......PPPPPPP.......',
        '......PPPPPPP.......',
        '.....SSSSSSSSS......',
        '.....PPPPPPPPP......',
        '.....PPPPPPPPP......',
        '.....PPPP.PPPP......',
        '......333..222......',
        '......333..222......',
        '......333..222......',
        '......333..222......',
        '......www..222......',
        '.....kkkk..222......',
        '.....kkkkk.www......',
        '.....wwwwwkkkk......',
        '..........kkkkk.....',
        '..........kkkkk.....',
        '..........wwwww.....',
      ],
    },
    tir: {
      center: 10,
      head: { x: 4, y: 7 },
      number: { x: 7, y: 25, width: 7 },
      ball: { x: 11, y: 2 },
      expression: 'concentree',
      rows: [
        '......................',
        '......................',
        '......................',
        '......................',
        '....222........333....',
        '....222........333....',
        '....222........333....',
        '...222..........333...',
        '..222............333..',
        '..222.............333.',
        '.222..............333.',
        '.222..............333.',
        '.222..............333.',
        '.222..............333.',
        '.222..............333.',
        '.222..............333.',
        '.222..............333.',
        '.222..............333.',
        '.222..............333.',
        '.222..............333.',
        '.222..............333.',
        '..222....222.....333..',
        '...2222PP222PP3333....',
        '.....22PPPPPPPP33.....',
        '......PPPPPPPPP.......',
        '......PPPPPPPPP.......',
        '......PPPPPPPPP.......',
        '......PPPPPPPPP.......',
        '......PPPPPPPPP.......',
        '.......PPPPPPP........',
        '.......PPPPPPP........',
        '.......PPPPPPP........',
        '.......PPPPPPP........',
        '......SSSSSSSSS.......',
        '......PPPPPPPPP.......',
        '......PPPPPPPPP.......',
        '......PPPP.PPPP.......',
        '.......222..333.......',
        '.......222..333.......',
        '.......222..333.......',
        '.......www..www.......',
        '......kkkk..kkkk......',
        '......kkkkk.kkkkk.....',
        '......wwwww.wwwww.....',
        '......................',
        '......................',
        '......................',
        '......................',
      ],
    },
  },
};

export const CANDIDATE_STYLES: readonly CandidateStyle[] = [STYLE_A, STYLE_B, STYLE_C];
